openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /djtutapp/student/:
    get:
      operationId: listStudents
      description: List all students, or create a new student.
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - djtutapp
